title: Example Pup Quiz
display_question_numbers: false # TODO re-enable after positioning is fixed
custom_css: |
  .reveal ol { list-style-type: upper-alpha; }
  .answer { color: red }
  .source {
      font-size: x-small;
  }
  .source::before {
      content: "Source: ";
  }
  .question_number { /* TODO */
      position: absolute;
      top: 0;
      left: 0;
  }
