title: Example Pup Quiz
worksheet_title: "Example Pup Quiz | Team name:"
display_question_numbers: false  # TODO re-enable after positioning is fixed
# maybe using data-state and state events
revealjs_theme: dracula
custom_css: |
  .answer { color: red }
  .source {
      font-size: calc(var(--r-main-font-size) * 0.75);
  }
  .source::before {
      content: "Source: ";
  }
  #question_number {
      position: absolute;
      top: 5%;
      left: 5%;
      font-family: var(--r-main-font);
      font-size: var( --r-heading3-size);
      font-weight: normal;
      color: var(--r-main-color);
  }
